services:
  db:
    image: postgres:16
    container_name: vendr_db
    environment:
      POSTGRES_DB: vendr
      POSTGRES_USER: vendr
      POSTGRES_PASSWORD: vendr
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
